["defaults"]
exclude = ["format", "spell"]

[[ignore."cpukit/dev"]]
files = ["cpukit/dev/iovprintf.c"]

[[ignore."cpukit/include"]]
files = [
    "cpukit/include/arpa/ftp.h",
    "cpukit/include/crypt.h",
    "cpukit/include/dlfcn.h",
    "cpukit/include/fdt.h",
    "cpukit/include/libfdt_env.h",
    "cpukit/include/libfdt.h",
    "cpukit/include/link_elf.h",
    "cpukit/include/link.h",
    "cpukit/include/md4.h",
    "cpukit/include/md5.h",
    "cpukit/include/mghttpd/mongoose.h",
    "cpukit/include/rtems/jffs2.h",
    "cpukit/include/rtems/mouse_parser.h",
    "cpukit/include/sha224.h",
    "cpukit/include/sha256.h",
    "cpukit/include/sha384.h",
    "cpukit/include/sha512.h",
    "cpukit/include/sha512t.h",
    "cpukit/include/sys/_ffcounter.h",
    "cpukit/include/sys/cdefs_elf.h",
    "cpukit/include/sys/endian.h",
    "cpukit/include/sys/event.h",
    "cpukit/include/sys/exec_elf.h",
    "cpukit/include/sys/priority.h",
    "cpukit/include/sys/statvfs.h",
    "cpukit/include/sys/timeffc.h",
    "cpukit/include/sys/timepps.h",
    "cpukit/include/sys/timetc.h",
    "cpukit/include/sys/timex.h",
    "cpukit/include/sys/utsname.h",
    "cpukit/include/uuid/uuid.h",
    "cpukit/include/xz.h",
    "cpukit/include/zconf.h",
    "cpukit/include/zlib.h"
]

[[ignore."cpukit/include/machine"]]
files = ["cpukit/include/machine/*.h"]

[[ignore."cpukit/jffs2"]]
files = [
    "cpukit/libfs/src/jffs2/include/linux/jffs2.h",
    "cpukit/libfs/src/jffs2/src/acl.h",
    "cpukit/libfs/src/jffs2/src/build.c",
    "cpukit/libfs/src/jffs2/src/compat-crc32.c",
    "cpukit/libfs/src/jffs2/src/compr_rtime.c",
    "cpukit/libfs/src/jffs2/src/compr_zlib.c",
    "cpukit/libfs/src/jffs2/src/compr_rubin.c",
    "cpukit/libfs/src/jffs2/src/compr.c",
    "cpukit/libfs/src/jffs2/src/compr.h",
    "cpukit/libfs/src/jffs2/src/debug.c",
    "cpukit/libfs/src/jffs2/src/debug.h",
    "cpukit/libfs/src/jffs2/src/dir-rtems.c",
    "cpukit/libfs/src/jffs2/src/erase.c",
    "cpukit/libfs/src/jffs2/src/flashio.c",
    "cpukit/libfs/src/jffs2/src/fs-rtems.c",
    "cpukit/libfs/src/jffs2/src/gc.c",
    "cpukit/libfs/src/jffs2/src/jffs2_fs_i.h",
    "cpukit/libfs/src/jffs2/src/jffs2_fs_sb.h",
    "cpukit/libfs/src/jffs2/src/malloc-rtems.c",
    "cpukit/libfs/src/jffs2/src/nodelist.c",
    "cpukit/libfs/src/jffs2/src/nodelist.h",
    "cpukit/libfs/src/jffs2/src/nodemgmt.c",
    "cpukit/libfs/src/jffs2/src/read.c",
    "cpukit/libfs/src/jffs2/src/readinode.c",
    "cpukit/libfs/src/jffs2/src/scan.c",
    "cpukit/libfs/src/jffs2/src/summary.h",
    "cpukit/libfs/src/jffs2/src/wbuf.c",
    "cpukit/libfs/src/jffs2/src/write.c",
    "cpukit/libfs/src/jffs2/src/xattr.h"
]

[[ignore."cpukit/libcrypt"]]
files = ["cpukit/libcrypt/*.c"]

[[ignore."cpukit/libcsupport"]]
files = [
    "cpukit/libcsupport/src/cfmakeraw.c",
    "cpukit/libcsupport/src/cfmakesane.c",
    "cpukit/libcsupport/src/realpath.c"
]

[[ignore."cpukit/libmd"]]
files = ["cpukit/libmd/*.c"]

[[ignore."cpukit/libdl"]]
files = [
    "cpukit/libdl/fastlz.c",
    "cpukit/libdl/fastlz.h"
]

[[ignore."cpukit/dtc"]]
files = [
    "cpukit/dtc/libfdt/*.c",
    "cpukit/dtc/libfdt/*.h",
    "cpukit/dtc/README.license",
    "cpukit/dtc/VERSION"
]

[[ignore."cpukit/mghttpd"]]
files = [
    "cpukit/mghttpd/mongoose.c",
]

[[ignore."cpukit/mouse"]]
files = ["cpukit/libmisc/mouse/mouse_parser.c"]

[[ignore."cpukit/score/cpu"]]
files = [
    "cpukit/score/cpu/i386/include/machine/elf_machdep.h",
    "cpukit/score/cpu/m68k/include/machine/elf_machdep.h",
    "cpukit/score/cpu/mips/include/machine/elf_machdep.h",
    "cpukit/score/cpu/nios2/include/machine/elf_machdep.h",
    "cpukit/score/cpu/sparc/include/machine/elf_machdep.h",
    "cpukit/score/cpu/x86_64/include/machine/elf_machdep.h"
]

[[ignore."cpukit/score/kern"]]
files = [
    "cpukit/score/src/kern_ntptime.c",
    "cpukit/score/src/kern_tc.c"
]

[[ignore."cpukit/shell"]]
files = [
    "cpukit/libmisc/shell/cat_file.c",
    "cpukit/libmisc/shell/cmds.c",
    "cpukit/libmisc/shell/cmp-ls.c",
    "cpukit/libmisc/shell/dd-args.c",
    "cpukit/libmisc/shell/dd-conv_tab.c",
    "cpukit/libmisc/shell/dd-conv.c",
    "cpukit/libmisc/shell/dd-misc.c",
    "cpukit/libmisc/shell/dd-position.c",
    "cpukit/libmisc/shell/dd.h",
    "cpukit/libmisc/shell/err.c",
    "cpukit/libmisc/shell/err.h",
    "cpukit/libmisc/shell/errx.c",
    "cpukit/libmisc/shell/extern-cp.h",
    "cpukit/libmisc/shell/extern-dd.h",
    "cpukit/libmisc/shell/extern-ls.h",
    "cpukit/libmisc/shell/fdisk.c",
    "cpukit/libmisc/shell/filemode.c",
    "cpukit/libmisc/shell/fts.c",
    "cpukit/libmisc/shell/fts.h",
    "cpukit/libmisc/shell/hexdump-conv.c",
    "cpukit/libmisc/shell/hexdump-display.c",
    "cpukit/libmisc/shell/hexdump-odsyntax.c",
    "cpukit/libmisc/shell/hexdump-parse.c",
    "cpukit/libmisc/shell/hexdump.h",
    "cpukit/libmisc/shell/hexsyntax.c",
    "cpukit/libmisc/shell/login_check.c",
    "cpukit/libmisc/shell/login_prompt.c",
    "cpukit/libmisc/shell/main_alias.c",
    "cpukit/libmisc/shell/main_blkstats.c",
    "cpukit/libmisc/shell/main_blksync.c",
    "cpukit/libmisc/shell/main_cat.c",
    "cpukit/libmisc/shell/main_cd.c",
    "cpukit/libmisc/shell/main_chdir.c",
    "cpukit/libmisc/shell/main_chmod.c",
    "cpukit/libmisc/shell/main_chroot.c",
    "cpukit/libmisc/shell/main_cmdchmod.c",
    "cpukit/libmisc/shell/main_cmdchown.c",
    "cpukit/libmisc/shell/main_cmdls.c",
    "cpukit/libmisc/shell/main_cp.c",
    "cpukit/libmisc/shell/main_cpuinfo.c",
    "cpukit/libmisc/shell/main_cpuuse.c",
    "cpukit/libmisc/shell/main_date.c",
    "cpukit/libmisc/shell/main_dd.c",
    "cpukit/libmisc/shell/main_debugrfs.c",
    "cpukit/libmisc/shell/main_df.c",
    "cpukit/libmisc/shell/main_dir.c",
    "cpukit/libmisc/shell/main_echo.c",
    "cpukit/libmisc/shell/main_edit.c",
    "cpukit/libmisc/shell/main_exit.c",
    "cpukit/libmisc/shell/main_flashdev.c",
    "cpukit/libmisc/shell/main_getenv.c",
    "cpukit/libmisc/shell/main_halt.c",
    "cpukit/libmisc/shell/main_help.c",
    "cpukit/libmisc/shell/main_hexdump.c",
    "cpukit/libmisc/shell/main_i2cdetect.c",
    "cpukit/libmisc/shell/main_i2cget.c",
    "cpukit/libmisc/shell/main_i2cset.c",
    "cpukit/libmisc/shell/main_id.c",
    "cpukit/libmisc/shell/main_ln.c",
    "cpukit/libmisc/shell/main_logoff.c",
    "cpukit/libmisc/shell/main_ls.c",
    "cpukit/libmisc/shell/main_lsof.c",
    "cpukit/libmisc/shell/main_mallocinfo.c",
    "cpukit/libmisc/shell/main_md5.c",
    "cpukit/libmisc/shell/main_mdump.c",
    "cpukit/libmisc/shell/main_medit.c",
    "cpukit/libmisc/shell/main_mfill.c",
    "cpukit/libmisc/shell/main_mkdir.c",
    "cpukit/libmisc/shell/main_mknod.c",
    "cpukit/libmisc/shell/main_mkrfs.c",
    "cpukit/libmisc/shell/main_mmove.c",
    "cpukit/libmisc/shell/main_mount.c",
    "cpukit/libmisc/shell/main_msdosfmt.c",
    "cpukit/libmisc/shell/main_mv.c",
    "cpukit/libmisc/shell/main_perioduse.c",
    "cpukit/libmisc/shell/main_profreport.c",
    "cpukit/libmisc/shell/main_pwd.c",
    "cpukit/libmisc/shell/main_rm.c",
    "cpukit/libmisc/shell/main_rmdir.c",
    "cpukit/libmisc/shell/main_rtc.c",
    "cpukit/libmisc/shell/main_rtems.c",
    "cpukit/libmisc/shell/main_rtrace.c",
    "cpukit/libmisc/shell/main_setenv.c",
    "cpukit/libmisc/shell/main_sleep.c",
    "cpukit/libmisc/shell/main_spi.c",
    "cpukit/libmisc/shell/main_stackuse.c",
    "cpukit/libmisc/shell/main_time.c",
    "cpukit/libmisc/shell/main_top.c",
    "cpukit/libmisc/shell/main_tty.c",
    "cpukit/libmisc/shell/main_umask.c",
    "cpukit/libmisc/shell/main_unmount.c",
    "cpukit/libmisc/shell/main_unsetenv.c",
    "cpukit/libmisc/shell/main_whoami.c",
    "cpukit/libmisc/shell/main_wkspaceinfo.c",
    "cpukit/libmisc/shell/mknod-pack_dev.h",
    "cpukit/libmisc/shell/pathnames-mv.h",
    "cpukit/libmisc/shell/print_heapinfo.c",
    "cpukit/libmisc/shell/print-ls.c",
    "cpukit/libmisc/shell/pwcache.c",
    "cpukit/libmisc/shell/shell_cmdset.c",
    "cpukit/libmisc/shell/shell_getchar.c",
    "cpukit/libmisc/shell/shell_getprompt.c",
    "cpukit/libmisc/shell/shell_makeargs.c",
    "cpukit/libmisc/shell/shell_script.c",
    "cpukit/libmisc/shell/shell-wait-for-input.c",
    "cpukit/libmisc/shell/shell.c",
    "cpukit/libmisc/shell/shellconfig.c",
    "cpukit/libmisc/shell/sysexits.h",
    "cpukit/libmisc/shell/utils-cp.c",
    "cpukit/libmisc/shell/utils-ls.c",
    "cpukit/libmisc/shell/verr.c",
    "cpukit/libmisc/shell/verrx.c",
    "cpukit/libmisc/shell/vis.c",
    "cpukit/libmisc/shell/vis.h",
    "cpukit/libmisc/shell/vwarn.c",
    "cpukit/libmisc/shell/vwarnx.c",
    "cpukit/libmisc/shell/warn.c",
    "cpukit/libmisc/shell/warnx.c",
    "cpukit/libmisc/shell/write_file.c",
    "cpukit/libmisc/uuid/clear.c",
    "cpukit/libmisc/uuid/compare.c",
    "cpukit/libmisc/uuid/copy.c",
    "cpukit/libmisc/uuid/gen_uuid.c",
    "cpukit/libmisc/uuid/isnull.c",
    "cpukit/libmisc/uuid/pack.c",
    "cpukit/libmisc/uuid/parse.c",
    "cpukit/libmisc/uuid/unpack.c",
    "cpukit/libmisc/uuid/unparse.c",
    "cpukit/libmisc/uuid/uuid_time.c",
    "cpukit/libmisc/uuid/uuidd.h",
    "cpukit/libmisc/uuid/uuidP.h"
]

[[ignore."cpukit/xz"]]
files = [
    "cpukit/compression/xz/*.h",
    "cpukit/compression/xz/*.c"
]

[[ignore."cpukit/zlib"]]
files = [
    "cpukit/compression/zlib/*.c",
    "cpukit/compression/zlib/*.h",
    "cpukit/compression/zlib/doc/*",
    "cpukit/compression/zlib/ChangeLog.zlib",
    "cpukit/compression/zlib/FAQ"
]

# These files have test characters that fail the char test
[[ignore."testsuites/fstests/fsdosfsname01"]]
exclude = ["char"]
files = [
	"testsuites/fstests/fsdosfsname01/init.c",
	"testsuites/fstests/fsdosfsname01/create_files.cs",
	"testsuites/fstests/fsdosfsname01/files.h"
]

[[ignore."yaml"]]
files = [
    "yaml/*"
]
